### PR TITLE
Fix missing backslash in path

### PR DESCRIPTION
**Pull request by fma965**
https://github.com/Archomeda/lightfx-extender/issues/7

### CODE REVIEW

**Comment by Archomeda** [comment]
Hmm, took a quick look and it appears that there's some reformatting going on. Can you fix your 2 tabs to spaces?

**Comment by fma965** [comment]
That has to be a setting in my visual studio as i haven't done anything regarding tabs or spaces.

**Comment by Fma965** [comment]
On closer look it's github for windows doing it not visual studio.

**Comment by fma965** [comment]
OK done.

Tools->Options->Text Editor->All Languages->Tabs
Change Tab to use "Insert Spaces" instead of "Keep Tabs".

**Comment by Archomeda** [comment]
Okay, that's odd that GitHub for Windows does that. Then again, I don't use it. Oh well, learned something today. Great that you could fix it! I'll do some more testing when I get home.

**Comment by Archomeda** [comment]
Whoops, not GfW... read an old email.

**Comment by Archomeda** [comment]
Yeah, apparently VS has that as a default setting. But it's really annoying because not all text editors see 1 tab as 4 spaces, which makes it inconsistent.

**Comment by fma965** [comment]
No worries, I learnt something new too lol, never made a PR before.

CommandCenter is broke though but i'm working on my own implementation of that anyway :)

**Comment by Archomeda** [comment]
Seems to be working fine.

**Pull request merged**
